### ISSUE TITLE
Update circe-be version

### ISSUE THREAD

**Issue by mdlavallee92** [OHDSI/CirceR#10]
Would it be possible to update the underlying version of circe-be in the CirceR package to match the current version of circe-be used for webapi? We are using CirceR in OHDSI/Capr package to build the cohort query from json and want to match the output with webapi. 

Found updates to circe-be in the sql templates for queries (such as condition occurrence) that remove for example `C.CONDITION_CONCEPT_ID as TARGET_CONCEPT_ID` (image below from circe-be code history). Using CirceR we still see elements in red in the sql output.

Best,
Martin

![image](https://user-images.githubusercontent.com/44976592/110331800-8dec9180-7fed-11eb-9ba7-171bfa0ddcf5.png)

**Comment by chrisknoll** [comment]
Sure thing, btw: that column wasn't removed it's just added as 'additional columns', I believe.

**Comment by chrisknoll** [comment]
Version 1.0.0 of CirceR has been released with the latest relesae of Circe.
