### ISSUE TITLE
Feature Request: Implement Function to Convert JSON conceptSetExpression to ConceptSet Sql

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CirceR#39]
I'd like to propose a new feature for the CirceR package. The functionality I envision would enable CirceR to take a conceptSetExpression in JSON format and return the equivalent ConceptSet in OHDSI Sql format. This SQL would resolve the concept set expression and return concept id's when run on OMOP CDM using OHDSI tools. This would be similar to the SQL generated for resolved conceptSets in a cohort, ensuring consistency with the buildCohortQuery(expression, options) behavior.

**Use Case:**
This feature would be particularly useful to rapidly evaluate concept set expressions without going through the entire cohort building process. It is also aligned with some of our research where the unit of the phenotype is a concept set vs a cohort. Such functionality would be used in software like ConceptSetDiagnostics to rapidly exploring the build, validation and diagnostics of concept set expressions.

**Expected Outcome:**
The expected outcome is a new function in CirceR that accepts a conceptSetExpression in JSON and returns the corresponding ConceptSetSql. This would mirror the internal process already used in cohort generation but made accessible for direct use.

Thank you for considering this feature request. I believe it would significantly augment the functionality and flexibility of the CirceR package.

**Comment by chrisknoll** [comment]
The documentation wasn't up to date, but I've just published.  Does this function satisfy this need:

https://ohdsi.github.io/CirceR/reference/buildConceptSetQuery.html
